mod utils;
use utils::platform::{bundled_executable, default_output_dir, find_on_path};
use utils::*;

use clap::{ArgGroup, Parser};
use std::error::Error;
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;
use yt_dlp::Downloader;
use yt_dlp::client::deps::{Libraries, LibraryInstaller};
use yt_dlp::model::Video;
use yt_dlp::model::playlist::{Playlist, PlaylistEntry};
use yt_dlp::utils::validation::sanitize_filename;

/// Resolve a yt-dlp `--js-runtimes` value with an absolute executable path when possible.
fn resolve_js_runtime(explicit: Option<&str>) -> Option<String> {
    if let Some(runtime) = explicit {
        if runtime.contains(':') {
            return Some(runtime.to_string());
        }
        if let Some(path) = find_on_path(runtime) {
            return Some(format!("{}:{}", runtime, path.display()));
        }
        return Some(runtime.to_string());
    }

    for name in ["deno", "node"] {
        if let Some(path) = find_on_path(name) {
            return Some(format!("{name}:{}", path.display()));
        }
    }
    None
}

/// yt-dlp loads `yt-dlp.conf` from the same directory as the binary (portable config).
/// The yt-dlp crate's metadata extractors do not receive `Downloader::with_args`, so this
/// file is how we ensure `--js-runtimes` applies to fetch commands too.
fn write_ytdlp_portable_config(libraries_dir: &Path, js_runtime: &str) -> Result<(), TestError> {
    let config_path = libraries_dir.join("yt-dlp.conf");
    let content = format!(
        "# Auto-generated by youtube_downloader\n--js-runtimes {js_runtime}\n"
    );
    fs::write(&config_path, content)?;
    println!("Wrote yt-dlp config: {}", config_path.display());
    Ok(())
}

#[derive(Parser, Debug)]
#[command(group(
    ArgGroup::new("source")
        .required(true)
        .args(["url", "list"])
))]
struct Args {
    #[arg(short, long, group = "source", help = "YouTube video URL")]
    url: Option<String>,
    #[arg(
        short = 'l',
        long = "list",
        group = "source",
        help = "YouTube playlist URL (watch URL with list= is supported)"
    )]
    list: Option<String>,
    #[arg(
        short,
        long,
        help = "Output filename override for single --url downloads (sanitized; .mp4 added if missing)"
    )]
    file: Option<String>,
    #[arg(short, long, default_value_t = default_output_dir())]
    output: String,
    #[arg(
        long = "wait-between-playlist-downloads",
        default_value_t = 60,
        help = "Seconds to wait between playlist downloads (default: 60)"
    )]
    wait_between_playlist_downloads: u64,
    #[arg(
        long = "playlist-start",
        requires = "list",
        help = "1-based playlist index to start from (e.g. 9 for index=9 in the URL)"
    )]
    playlist_start: Option<usize>,
    #[arg(
        long = "cookies-from-browser",
        help = "Use browser cookies for YouTube login/age-restricted videos (e.g. chrome, safari, firefox)"
    )]
    cookies_from_browser: Option<String>,
    #[arg(
        long = "cookies",
        help = "Path to a Netscape-format cookies file"
    )]
    cookies: Option<PathBuf>,
    #[arg(
        long = "js-runtimes",
        help = "JavaScript runtime for YouTube (passed to yt-dlp), e.g. node or deno"
    )]
    js_runtimes: Option<String>,
    #[clap(short, long, default_value = "best")]
    quality: String,
}

#[derive(Debug)]
enum TestError {
    UrlDownloadError(String),
    YtDlpError(String),
    IOError(String),
}

impl fmt::Display for TestError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            TestError::UrlDownloadError(description) => write!(f, "Generic error: {}", description),
            TestError::YtDlpError(description) => {
                write!(f, "YouTube downloader error: {}", description)
            }
            TestError::IOError(description) => write!(f, "IO error: {}", description),
        }
    }
}

impl Error for TestError {}

impl From<yt_dlp::error::Error> for TestError {
    fn from(err: yt_dlp::error::Error) -> Self {
        TestError::YtDlpError(err.to_string())
    }
}

impl From<std::io::Error> for TestError {
    fn from(err: std::io::Error) -> Self {
        TestError::IOError(err.to_string())
    }
}

fn output_filename_for_video(video: &Video, name_override: Option<&str>) -> String {
    if let Some(name) = name_override {
        let name = name.trim();
        if !name.is_empty() {
            let sanitized = sanitize_filename(name);
            if !sanitized.is_empty() {
                return if sanitized.ends_with(".mp4") {
                    sanitized
                } else {
                    format!("{sanitized}.mp4")
                };
            }
        }
    }

    let stem = sanitize_filename(&video.title);
    let stem = if stem.is_empty() || stem == "download" {
        video.id.as_str()
    } else {
        stem.as_str()
    };
    format!("{stem}.mp4")
}

fn output_dir_str(output_dir: &PathBuf) -> Result<&str, TestError> {
    output_dir
        .to_str()
        .ok_or_else(|| TestError::UrlDownloadError("Invalid output directory".to_string()))
}

async fn download_one_video(
    downloader: &Downloader,
    output_dir: &PathBuf,
    video: &Video,
    name_override: Option<&str>,
) -> Result<PathBuf, TestError> {
    let output_filename = output_filename_for_video(video, name_override);
    println!("Output filename: {}", output_filename);

    let output_path = output_dir.join(&output_filename);
    println!("Output path: {}", output_path.display());

    if output_path.exists() {
        match fs::remove_file(&output_path) {
            Ok(()) => println!("Deleted existing file: {}", output_path.display()),
            Err(e) => println!("Failed to delete existing file: {}", e),
        }
    }

    println!("Downloading video...");
    let video_path = downloader.download_video(video, &output_filename).await?;
    println!("Successfully downloaded video to: {}", video_path.display());

    cleanup_temp_files(output_dir_str(output_dir)?, &video.id)?;

    Ok(video_path)
}

async fn download_single(
    downloader: &Downloader,
    output_dir: &PathBuf,
    url: &str,
    name_override: Option<&str>,
) -> Result<(), TestError> {
    println!("YouTube url: {}", url);

    let youtube_id = extract_youtube_id(url)
        .ok_or_else(|| TestError::UrlDownloadError("Error: YouTube id not found.".to_string()))?;
    println!("YouTube id: {}", youtube_id);

    println!("Fetching video metadata...");
    let video = downloader.fetch_video_infos(url).await?;
    println!("Title: {}", video.title);

    download_one_video(downloader, output_dir, &video, name_override).await?;
    Ok(())
}

fn entry_one_based_index(entry: &PlaylistEntry, position: usize) -> usize {
    entry.index.unwrap_or(position)
}

fn playlist_entries_in_range<'a>(
    playlist: &'a Playlist,
    playlist_start: Option<usize>,
) -> Result<Vec<&'a PlaylistEntry>, TestError> {
    let candidates: Vec<_> = playlist
        .entries
        .iter()
        .enumerate()
        .filter(|(i, entry)| {
            if let Some(start) = playlist_start {
                if start < 1 {
                    return false;
                }
                entry_one_based_index(entry, i + 1) >= start
            } else {
                true
            }
        })
        .map(|(_, entry)| entry)
        .collect();

    if let Some(start) = playlist_start {
        if start < 1 {
            return Err(TestError::UrlDownloadError(
                "--playlist-start must be >= 1 (1-based index).".to_string(),
            ));
        }
        println!(
            "Starting from playlist index {} ({} entries in range)",
            start,
            candidates.len()
        );
    }

    Ok(candidates
        .into_iter()
        .filter(|e| e.is_available())
        .collect())
}

async fn download_playlist_sequential(
    downloader: &Downloader,
    output_dir: &PathBuf,
    list_url: &str,
    wait_secs: u64,
    playlist_start: Option<usize>,
) -> Result<(), TestError> {
    println!("Playlist url: {}", list_url);

    println!("Fetching playlist metadata...");
    let playlist = downloader.fetch_playlist_infos(list_url).await?;
    println!(
        "Playlist: {} ({} entries)",
        playlist.title,
        playlist.entry_count()
    );

    let entries = playlist_entries_in_range(&playlist, playlist_start)?;
    let unavailable_in_range = playlist
        .entries
        .iter()
        .enumerate()
        .filter(|(i, entry)| {
            playlist_start.is_none_or(|start| entry_one_based_index(entry, i + 1) >= start)
        })
        .filter(|(_, entry)| !entry.is_available())
        .count();
    if unavailable_in_range > 0 {
        println!("Skipping {} unavailable entries in range", unavailable_in_range);
    }
    if entries.is_empty() {
        return Err(TestError::UrlDownloadError(
            "No downloadable videos in playlist.".to_string(),
        ));
    }

    let total = entries.len();
    let wait = Duration::from_secs(wait_secs);

    for (i, entry) in entries.iter().enumerate() {
        let position = i + 1;
        let display_index = entry.index.unwrap_or(position);
        println!(
            "\n--- Playlist item {}/{} (index {}): {} ---",
            position, total, display_index, entry.title
        );

        let video = match downloader.fetch_video_infos(&entry.url).await {
            Ok(video) => video,
            Err(e) => {
                eprintln!("Failed to fetch metadata for {}: {}", entry.id, e);
                if position < total {
                    println!("Waiting {} seconds before next download...", wait_secs);
                    tokio::time::sleep(wait).await;
                }
                continue;
            }
        };
        match download_one_video(downloader, output_dir, &video, None).await {
            Ok(_) => {}
            Err(e) => {
                eprintln!("Failed to download {}: {}", entry.id, e);
            }
        }

        if position < total {
            println!("Waiting {} seconds before next download...", wait_secs);
            tokio::time::sleep(wait).await;
        }
    }

    println!("\nPlaylist download pass finished ({} videos).", total);
    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), TestError> {
    let args = Args::parse();

    let libraries_dir = PathBuf::from("libs");
    let output_dir = PathBuf::from(&args.output);
    fs::create_dir_all(&output_dir)?;

    let youtube = bundled_executable(&libraries_dir, "yt-dlp");
    let ffmpeg = bundled_executable(&libraries_dir, "ffmpeg");

    if !youtube.exists() {
        println!("Downloading youtube library.");
        let installer = LibraryInstaller::new(libraries_dir.clone());
        installer.install_youtube(None).await?;
    }
    if !ffmpeg.exists() {
        println!("Downloading ffmpeg library.");
        let installer = LibraryInstaller::new(libraries_dir.clone());
        installer.install_ffmpeg(None).await?;
    }

    if let Some(runtimes) = resolve_js_runtime(args.js_runtimes.as_deref()) {
        println!("Using JavaScript runtime: {}", runtimes);
        write_ytdlp_portable_config(&libraries_dir, &runtimes)?;
    } else {
        eprintln!(
            "Warning: no JS runtime found (install deno or node). \
             YouTube downloads may fail; see https://github.com/yt-dlp/yt-dlp/wiki/EJS"
        );
    }

    let libraries = Libraries::new(youtube, ffmpeg);

    println!("Updating yt-dlp executable.");
    let mut builder = Downloader::builder(libraries, output_dir.clone())
        .with_timeout(Duration::from_secs(300));
    if let Some(browser) = &args.cookies_from_browser {
        println!("Using cookies from browser: {}", browser);
        builder = builder.with_cookies_from_browser(browser);
    }
    if let Some(cookies) = &args.cookies {
        println!("Using cookies file: {}", cookies.display());
        builder = builder.with_cookies(cookies);
    }
    let downloader = builder.build().await?;
    downloader.update_downloader().await?;
    println!("Done.");

    if let Some(url) = &args.url {
        download_single(&downloader, &output_dir, url, args.file.as_deref()).await?;
    } else if let Some(list_url) = &args.list {
        download_playlist_sequential(
            &downloader,
            &output_dir,
            list_url,
            args.wait_between_playlist_downloads,
            args.playlist_start,
        )
        .await?;
    }

    Ok(())
}
